version: "3.9"
services:
  app:
    image: registry-service-app
    container_name: Registry_service_app
    build:
      context: .
    ports:
      - "8761:8761"
    networks:
      - backend_network

networks:
  backend_network:
    external: true

#
# Commands:
#
# docker-compose up                -> used to create a docker container
# docker-compose down              -> used to destroy a docker container
#