version: "3.9"
services:
  app:
    image: cloud-configuration-server-app
    container_name: Cloud_configuration_server_app
    build:
      context: .
    ports:
      - 9001:9001
    networks:
      - backend_network

networks:
  backend_network:
    external: true

#
# Commands:
#
# docker-compose up                -> used to create a docker container
# docker-compose down              -> used to destroy a docker container
#