services:
  app:
    image: 2auth.jwt.app
    container_name: Authentification-Authorization-JWT-app
    build:
      context: .
    ports:
      - 8090:8090
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trainingManagementPlatform

  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 5431:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: trainingManagementPlatform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin