# Custom port
server:
  port: 9001

spring:
  # Name the application
  application:
    name: CLOUD-CONFIGURATION-SERVER

  # Cloud configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/undervon/Training-Management-Platform-Configuration-Server
          clone-on-start: true