services:
  postgres:
    image: postgres
    container_name: postgres_db_for_build
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ../images/admin-icon.png:/docker-entrypoint-initdb.d/admin-icon.png
      - ../images/user-icon.png:/docker-entrypoint-initdb.d/user-icon.png
    environment:
      POSTGRES_DB: trainingManagementPlatform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      TZ: Europe/Bucharest

#
# Commands:
#
# docker-compose up                -> used to create a docker container; the first time it is used, a docker image is creating (with postgres)
# docker-compose down              -> used to destroy a docker container
#